steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA"
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA"
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud run deploy $_SERVICE_NAME \
          --image "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA" \
          --region $_DEPLOY_REGION \
          --platform $_PLATFORM \
          --set-env-vars POSTGRES_URL=$_POSTGRES_URL,GOOGLE_CLIENT_ID=$_GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET=$_GOOGLE_CLIENT_SECRET,NEXTAUTH_URL=$_NEXTAUTH_URL,NEXTAUTH_SECRET=$_NEXTAUTH_SECRET,NEXT_PUBLIC_STREAM_API_KEY=$_NEXT_PUBLIC_STREAM_API_KEY,NEXT_PUBLIC_STREAM_API_SECRET=$_NEXT_PUBLIC_STREAM_API_SECRET \
          --allow-unauthenticated \
          --timeout 2400s
timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA"
