steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA"
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA"
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - "-c"
      - |
        POSTGRES_URL=$(gcloud secrets versions access latest --secret="postgres-url")
        GOOGLE_CLIENT_ID=$(gcloud secrets versions access latest --secret="google-client-id")
        GOOGLE_CLIENT_SECRET=$(gcloud secrets versions access latest --secret="google-client-secret")
        NEXTAUTH_URL=$(gcloud secrets versions access latest --secret="nextauth-url")
        NEXTAUTH_SECRET=$(gcloud secrets versions access latest --secret="nextauth-secret")
        NEXT_PUBLIC_STREAM_API_KEY=$(gcloud secrets versions access latest --secret="next-public-stream-api-key")
        NEXT_PUBLIC_STREAM_API_SECRET=$(gcloud secrets versions access latest --secret="next-public-stream-api-secret")

        gcloud run deploy $_SERVICE_NAME \
          --image "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA" \
          --region $_DEPLOY_REGION \
          --platform $_PLATFORM \
          --set-env-vars "POSTGRES_URL=$POSTGRES_URL,GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET,NEXTAUTH_URL=$NEXTAUTH_URL,NEXTAUTH_SECRET=$NEXTAUTH_SECRET,NEXT_PUBLIC_STREAM_API_KEY=$NEXT_PUBLIC_STREAM_API_KEY,NEXT_PUBLIC_STREAM_API_SECRET=$NEXT_PUBLIC_STREAM_API_SECRET" \
          --allow-unauthenticated
timeout: 1200s
images:
  - "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA"
