name: meetcode
on:
push:
branches:
  - main
  - master

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.REGION }}
  REPO_NAME: ${{ secrets.REPO_NAME }}

jobs:
  build-and-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest
  steps:
    - name: Checkout
    uses: actions/checkout@v3


# Authentication with Google Cloud
    - id: gcloud-auth
      uses: google-github-actions/auth@v0
      with:
        credentials.json: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}

# Setup cloud CLI SDK
    - name: Setup gcloud CLI SDK
      run: google-github-actions/setup-gcloud@v0

    - name: Authorize Docker push to Google Artifact Registry
      run: gcloud auth configure-docker $REGION-docker.pkg.dev

    - name: Build the container image
      run: |
        docker build -t $REGION-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:${{ github.sha }} .

    - name: Push the container image to Google Artifact Registry
      run: |
        docker push $REGION-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:${{ github.sha }}

    - name: Deploy the container image to Cloud Run
      run: |
        gcloud run deploy ${{ env.REPO_NAME }} \
        --image $REGION-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:${{ github.sha }} \
        --platform "managed" \
        --region ${{ env.REGION }} \
        --allow-unauthenticated